package FinanceApp;


/**
* FinanceApp/AuthServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Finance.idl
* Tuesday, January 6, 2026 4:12:35 PM SGT
*/

abstract public class AuthServiceHelper
{
  private static String  _id = "IDL:FinanceApp/AuthService:1.0";

  public static void insert (org.omg.CORBA.Any a, FinanceApp.AuthService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FinanceApp.AuthService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FinanceApp.AuthServiceHelper.id (), "AuthService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FinanceApp.AuthService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuthServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FinanceApp.AuthService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FinanceApp.AuthService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FinanceApp.AuthService)
      return (FinanceApp.AuthService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FinanceApp._AuthServiceStub stub = new FinanceApp._AuthServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FinanceApp.AuthService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FinanceApp.AuthService)
      return (FinanceApp.AuthService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FinanceApp._AuthServiceStub stub = new FinanceApp._AuthServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
