package FinanceApp;

/**
* FinanceApp/FinanceServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Finance.idl
* Tuesday, January 6, 2026 4:12:35 PM SGT
*/

public final class FinanceServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public FinanceApp.FinanceService value = null;

  public FinanceServiceHolder ()
  {
  }

  public FinanceServiceHolder (FinanceApp.FinanceService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FinanceApp.FinanceServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FinanceApp.FinanceServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FinanceApp.FinanceServiceHelper.type ();
  }

}
