package FinanceApp;


/**
* FinanceApp/AuthServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Finance.idl
* Tuesday, January 6, 2026 4:12:35 PM SGT
*/

public interface AuthServiceOperations 
{
  boolean register (String username, String password);
  boolean login (String username, String password);
} // interface AuthServiceOperations
