package FinanceApp;

/**
* FinanceApp/AuthServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Finance.idl
* Tuesday, January 6, 2026 4:12:35 PM SGT
*/

public final class AuthServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public FinanceApp.AuthService value = null;

  public AuthServiceHolder ()
  {
  }

  public AuthServiceHolder (FinanceApp.AuthService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FinanceApp.AuthServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FinanceApp.AuthServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FinanceApp.AuthServiceHelper.type ();
  }

}
