package FinanceApp;


/**
* FinanceApp/FinanceServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Finance.idl
* Tuesday, January 6, 2026 4:12:35 PM SGT
*/

public abstract class FinanceServicePOA extends org.omg.PortableServer.Servant
 implements FinanceApp.FinanceServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addTransaction", new java.lang.Integer (0));
    _methods.put ("getTransactions", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FinanceApp/FinanceService/addTransaction
       {
         String username = in.read_string ();
         String type = in.read_string ();
         double amount = in.read_double ();
         String note = in.read_string ();
         boolean $result = false;
         $result = this.addTransaction (username, type, amount, note);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // FinanceApp/FinanceService/getTransactions
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getTransactions (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FinanceApp/FinanceService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FinanceService _this() 
  {
    return FinanceServiceHelper.narrow(
    super._this_object());
  }

  public FinanceService _this(org.omg.CORBA.ORB orb) 
  {
    return FinanceServiceHelper.narrow(
    super._this_object(orb));
  }


} // class FinanceServicePOA
