package FinanceApp;


/**
* FinanceApp/FinanceServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Finance.idl
* Tuesday, January 6, 2026 4:12:35 PM SGT
*/

public interface FinanceServiceOperations 
{
  boolean addTransaction (String username, String type, double amount, String note);
  String getTransactions (String username);
} // interface FinanceServiceOperations
